#!/bin/sh
#
# Start debugfs....
#

case "$1" in
  start)
	echo "Starting debugfs..."
	mount -t debugfs debugfs /sys/kernel/debug
	cat /sys/kernel/debug/gpio
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
