#!/bin/sh
#
# Mounting configfs....
#

case "$1" in
  start)
	echo "Mounting configfs...."
	mount -t configfs configfs /sys/kernel/config
	ls /sys/kernel/config
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
