#!/bin/bash

if ! [ -f ${ELDS}/rootfs/${ELDS_BOARD}/${ELDS_CROSS_TUPLE}/host/usr/bin/xz ]; then
	printf "***** FIX MISSING HOST 'xz' *****\n"
	ln -s /usr/bin/xz ${ELDS}/rootfs/${ELDS_BOARD}/${ELDS_CROSS_TUPLE}/host/usr/bin/xz
fi
