#!/bin/bash

TARGET=$1

# Preserve target (Ideally the result of 'make solution')
cp -a ${TARGET} ${TARGET}-bare

# Update target file system
rsync -av ${ELDS}/common/rootfs/* ${TARGET}/ 2>/dev/null
rsync -av ${ELDS}/boards/${ELDS_BOARD}/rootfs/* ${TARGET}/ 2>/dev/null
rsync -av ${ELDS}/toolchain/${ELDS_CROSS_TUPLE}/${ELDS_CROSS_TUPLE}/debug-root/* ${TARGET}/ 2>/dev/null
printf "\n`cat ${TARGET}/etc/issue`\n\n" > ${TARGET}/etc/issue
