#!/bin/bash

TARGET=$1

# Preserve target (Ideally the result of 'make solution')
cp -a ${TARGET} ${TARGET}-bare

# Update target file system
rsync -av ${ELDS}/common/rootfs/* ${TARGET}/ 2>/dev/null
rsync -av ${ELDS}/boards/${ELDS_BOARD}/rootfs/* ${TARGET}/ 2>/dev/null
rsync -av ${ELDS}/toolchain/${ELDS_CROSS_TUPLE}/${ELDS_CROSS_TUPLE}/debug-root/* ${TARGET}/ 2>/dev/null
printf "\n`cat ${TARGET}/etc/issue`\n\n" > ${TARGET}/etc/issue

# Board Specific Modifications
case "${ELDS_BOARD}" in
	*am3517-evm*)
		mkdir -p ${TARGET}/media/BOOT
		printf "/dev/mmcblk0p1 /media/BOOT auto errors=remount-ro 0 1\n" >> ${TARGET}/etc/fstab
		;;
	*beagle-c4*)
		mkdir -p ${TARGET}/media/BOOT
		printf "/dev/mmcblk0p1 /media/BOOT auto errors=remount-ro 0 1\n" >> ${TARGET}/etc/fstab
		;;
	*olinuxino-maxi*)
		# ttyAMA0 is not working on my board (for now)
		printf "ttyAPP0\n" >> ${TARGET}/etc/securetty
		printf "console=ttyAPP0\n" > ${TARGET}/boot/uEnv.txt
		printf "ttyAPP0::respawn:/sbin/getty -L ttyAPP0 115200 vt102\n" >> ${TARGET}/etc/inittab
		;;
	*realview-pb*)
		;;
	*sama5d3-xpld*)
		mkdir -p ${TARGET}/media/BOOT
		printf "/dev/mmcblk0p1 /media/BOOT auto errors=remount-ro 0 1\n" >> ${TARGET}/etc/fstab
		;;
	*versatile-pb*)
		;;
	*)
		;;
esac

# Perform Misc. Development Host Operations
${ELDS}/scripts/fixup

