#!/bin/bash

usage()
{
	printf "USAGE: push <target-dir> mmc\n"
	printf "       push <target-dir> net <ip-address>\n"
}

if [ "x${2}" = "x" ]; then
	printf "Missing transfer type!\n"
	usage
	exit 1
fi

transfer_type=${2}

if [ "x${1}" = "x" ]; then
	printf "Missing target directory!\n"
	usage
	exit 1
fi

target_dir=${1}

send_list="boot lib/firmware lib/modules"

case "${transfer_type}" in
	mmc)
		if [ -d /media/$USER ]; then
			media="/media/$USER"
		else
			if [ -d /run/media/$USER ]; then
				media="/run/media/$USER"
			else
				printf "Unknown SD/MMC media directory location!\n"
				exit 1
			fi
		fi
		pushd ${target_dir}
		sudo rsync -aPR ${send_list} ${media}/rootfs/ && sync
		popd
		;;
	net)
		if [ "x${3}" = "x" ]; then
			printf "Missing IP address!\n"
			usage
			exit 1
		fi
		pushd ${target_dir}
		rsync -aPR ${send_list} root@${3}:/
		popd
		;;
	*)
		printf "Transfer type [${transfer_type}] not implemented.\n"
		usage
		exit 1
esac
